---
    - include_tasks: set_instance_facts.yml
    - include_tasks: setup_iam_instance_profile.yml
    - include_tasks: create_cloudwatch_user.yml
    - include_tasks: create_dirs.yml
    - include_tasks: copy_metric_scripts.yml
    - include_tasks: set_cronjobs.yml

